---
- name: Create Grafana directory in user's home
  file:
    path: "{{ grafana_install_dir }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: "0755"

- name: Create grafana opt directory 
  file:
    path: /opt/grafana
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: "0755"

- name: Create Dockerfile
  template:
    src: docker-compose.yml.j2
    dest: /opt/grafana/docker-compose.yml
    mode: "0644"
  notify: Restart grafana Container