---
- name: Update and upgrade Ubuntu
  hosts: minecraft_server
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

- name: Install packages in packages_debian
  hosts: all
  become: yes
  roles:
    - packages_debian

- name: Install Docker
  hosts: all
  become: yes
  roles:
    - docker

- name: Install dyndns
  hosts: minecraft_server
  become: yes
  roles:
    - dyndns

- name: Install prometheus Server
  hosts: minecraft_server
  become: yes
  roles:
    - prometheus
  
- name: Install grafana Server
  hosts: minecraft_server
  become: yes
  roles:
    - grafana

- name: Install Minecraft Paper Server
  hosts: minecraft_server
  become: yes
  roles:
    - minecraft_paper
  